### ISSUE TITLE
[ufo3k] Moving pens out of Robofab

### ISSUE THREAD

**Issue by moyogo** [robofab-developers/robofab#52]
There’s some interest in moving pens out of Robofab, maybe to fonttools or a separate library. @adrientetar @anthrotype @behdad @brawer @graphicore @jamesgk 
Robofab-devs, could this happen?

**Comment by graphicore** [comment]
:+1: 

I wrote recently in https://github.com/robofab-developers/robofab/issues/46#issuecomment-140086483:

> Well, I did not make up my mind completely yet. But with ufoJS I think it's far easier for me to move things around and rearrange them. So I'm thinking of a JavaScript library let's call it "penBox" where all the generally useful pens that are defined somewhere would be collected. That includes pens from fontTools, RoboFab and ufoLib. From RoboFab that would be all pens that don't require a direct RoboFab dependency i.e. a module from robofab.objects or so. The rationale is that I think the pen APIs are a great way to work with outlines and thus can be very useful for people even if they don't use ufoLib or RoboFab. I did so already in some occasions.
For the plan of splitting ufoLib and RoboFab I also think it could be a good idea to make a "penBox"` that contains all pens that are neither dependent on RoboFab nor on ufoLib. Instead RoboFab and ufoLib would import penBox.

**Comment by adrientetar** [comment]
Also put ufoLib into a separate repo would be a thing too. Nothing we can't do in our forks, of course.

**Comment by moyogo** [comment]
@adrientetar That’s addressed in #51. Sorry I should have pinged you guys.

**Comment by typesupply** [comment]
The pen protocol management has moved to ufoLib and ufoLib should be moved to be owned by the UFO spec (see my comment on #51). Thus, the protocol would become standardized or at least quasi-standardized until someone has time to fully document it. The only open question for me is: what pens should go along with it? As @graphicore wrote, there are some very good reasons to move any general use pens out of RoboFab. Which ones those are and where they should move is the real issue. I can kind of see them moving along with ufoLib, but it also seems kind of weird to make them officially part of the UFO spec. So, hm.

**Comment by adrientetar** [comment]
What do you think about putting them in fontTools? fontTools is basically, the things that you need to work with fonts regardless of whether you use robofab or defcon or sth. else. So I think it makes sense to put them in fontTools. 
Also, fontTools is already a dependency of robofab and some robofab subclass the base pens contained in fontTools so it makes all the more sense to me.

**Comment by typesupply** [comment]
fontTools has pens, but not pointPens. If fontTools wants to support pointPens too, then, yeah, that might be a good home for some of the more versatile pens. I still think that the pointPen protocol (any maybe the pen?) should be owned by the UFO spec.

**Comment by twardoch** [comment]
I'm in favor of aggregating the pens (including pointPens) into a separate package. The Pen API is great but I think the current dispersion across packages is somewhat confusing. A separate penBox package could be oragized a bit like the robofab "worlds", i.e. additional formats or apps could contribute their code there.

**Comment by adrientetar** [comment]
> fontTools has pens, but not pointPens.

I had not realized that. Is there any reason why pointPens are not fitting for fontTools?

**Comment by twardoch** [comment]
Also, a unified package would make it easier for people to decide where to contribute code. For example, if someone writes a "remove-overlap-pen" or a "cubic-to-quadratic-pen" or some other "effect" pens, currently it is not obvious where such contributions should be made.

**Comment by twardoch** [comment]
By "effect" I meant "filterPen". I really like the principle behind filterPen, and I think boolean ops (at least remove overlaps), cubic-to-quadratic (including some clever optimizations) and other such operations could be well-implemented as pens or filterPens, as a rule. 

I think even an autohinter should use the pen protocol (possibly extended). I think the pen protocol is the single best invention of the RoboFab team, and I think it should have a life of its own.

**Comment by anthrotype** [comment]
Thank you Tal.
I also think it would be good to keep the all the "concrete" pens in a unified package, e.g. `penLib`, `penTools` or whatever. Except for the AbstractPointPen class, they should be kept separate from the UFO spec reference implementation (which will become ufoLib).

> Is there any reason why pointPens are not fitting for fontTools?

It's not that the pointPen protocol isn't "fitting" for fontTools; simply it hasn't been "fitted" yet. But it shouldn't be hard to add a `.drawPoints` method to fonttools' Glyph objects. I'll see what I can do.

**Comment by adrientetar** [comment]
Cool, Cosimo. With this I think we can move the pens to fontTools, which to me makes most sense.

**Comment by twardoch** [comment]
I don't think it makes sense to move pens to fontTools. fontTools is 98% related to native font formats, primarily SFNT (.otf, .ttf), and most of the fontTools functionality is relatively low-level, and is not in any way tied to UFO, RoboFab or other such higher-level formats. Pens are pretty much at the opposite end of the spectrum where fontTools mostly operates in.

**Comment by adrientetar** [comment]
It uses quite some pens already to work with font data.

**Comment by graphicore** [comment]
Like @twardoch  I'd vote for a separate package, a `penBox`. I think fontTools  should be depending on that.

> … move the pens to fontTools, which to me makes most sense.

Not to me. Simply because pens can be useful even if you don't work with fonts. Just to draw vector graphics.

**Comment by anthrotype** [comment]
I think Adam is right. We could add the `drawPoint` methods to fonttools glyphs, so that they can work with point pens as well as segment pens. But that doesn't mean all the robofab pens should become part of fonttools.

**Comment by twardoch** [comment]
@adrientetar fontTools does use pens, but it also uses XML, Python strings and lists, and other things. I feel having pens in fontTools is like having a color management library sub-packaged into an HTML parser simply because at the time of the original writing it was a convenient place to put it. 

In the 1930s, the English actress Edith Evans bought a Renoir painting. A friend was having tea with her and said, “Edith, have they delivered the Renoir?”. “Yes. Yes, it’s here,” she said. “Well, can I see it?”, asked the friend. Edith Evans pointed to a corner spot on the wall, quite low and half behind a curtain and said “It’s over there!”. The friend looked at the painting and said, “Well, it’s lovely, Edith, but why did you hang it there?”. She said, “There was a hook!” 

To me, having pens in fontTools is a bit like that :)

**Comment by benkiel** [comment]
Another vote to put pens into it's own thing.

**Comment by twardoch** [comment]
In other words, I'd prefer to add an external dependency to fontTools so that the new 'glyphPens' (or whatever) package is needed for fontTools to build, possibly leaving a minimal fallback implementation inside fontTools, and have 'glyphPens' to live in a separate package. The pens conveptually don't really belong to fontTools or roboFab completely, but are a shared protocol, one that hopefully will enjoy a new set of contributions if refactored. Of course some backwards-compatible hooks ("redirects" of sort) could be added so that existing code doesn't break.

**Comment by twardoch** [comment]
'roboPens" might be a sensible package name to underline their heritage. Or 'glyphPens', which what they really are.

**Comment by anthrotype** [comment]
There's no need to add any new dependency to fontTools. If one wants to implement a pen that subscribes to the PointPen protocol, one does not need to `from roboPens import AbstractPointPen`.
It just needs to create a new class which has the four basic methods of any point pen: 'beginPath`, `endPath`, `addPoint` and `addComponent`.
If it walks like a PointPen, and quacks like a PointPen, it is a PointPen.

**Comment by twardoch** [comment]
Also from the organizational point of view: the pens have a different lifecycle that the rest of fontTools, and while @behdad is a great maintainer of fontTools, I don't think he's the right person to maintain the pens. The pens have indeed a tighter link to UFO. Perhaps one of the "active newcomers" (not in a negative way) like Cosimo or Adrien would be willing to maintain it? Someone who's closer to the "Robo/UFO" community, and who actually understands/uses pens extensively. I imagine that Tal wouldn't really jump up with joy at the prospect of maintaining yet another package. :)

**Comment by twardoch** [comment]
@anthrotype Good point :)

**Comment by behdad** [comment]
Not in fontmath?

**Comment by behdad** [comment]
I think PointToSegmentPen and SegmentToPointPen should live in fonttools, and the rest outside.

**Comment by graphicore** [comment]
> I think PointToSegmentPen and SegmentToPointPen should live in fonttools, and the rest outside.

If we have a library that hosts both, point pens and segment pens, why should the adapters between these live somewhere else?

**Comment by behdad** [comment]
> I think PointToSegmentPen and SegmentToPointPen should live in fonttools, and the rest outside.
> 
> If we have a library that hosts both, point pens and segment pens, why should the adapters between these live somewhere else?

If we do, agreed.

**Comment by anthrotype** [comment]
maybe because the `AbstractPen` (the protocol for all segment pens) was originally defined in `fontTools.pens.basePen` module. But in theory the latter could also become part of a shared pens library in which both segment and point pens coexist. Again, with duck typing one wouldn't need to depend on other packages if the only requirement is an abstract class.

**Comment by anthrotype** [comment]
@typesupply @adrientetar any updates on migrating robofab.pens to roboPens/penBox?

**Comment by adrientetar** [comment]
as I said [here](https://github.com/robofab-developers/robofab/issues/51#issuecomment-154827539), my current concern would be to move SegmentToPointPen and PointToSegmentPen to ufoLib, since ufoLib "owns" the pointPen protocol per what Tal said (which I think makes a lot of sense), PointToSegmentPen is the only remaining dependency of ufoLib to robofab.

**Comment by anthrotype** [comment]
if ufoLib doesn't want to maintain any dependency from penBox (or whatever), then it could implement its own converter pens (there's nothing fancy about them). Otherwise, it could simply import them from penBox once it goes live, instead of robofab.  

```
$ git grep robofab
Lib/ufoLib/glifLib.py:78:               from robofab.pens.adapterPens import PointToSegmentPen
```

**Comment by typesupply** [comment]
> any updates on migrating robofab.pens to roboPens/penBox?

I think a new repository for non-environment specific pens is a very good idea.

I've been thinking about the dependency issues. I think the converters should live inside of ufoLib. That makes sense to me as it isolates the implementation of the PointPen infrastructure and protocol. As you pointed out, this wouldn't necessarily require a dependency on ufoLib for penBox since the PointPen protocol is pretty simple and doesn't require any abstract infrastructure. (Whereas the Pen protocol does for handling quad <-> cubic conversion.) So, that's easy enough. The UFO spec should officially document the PointPen protocol somewhere to make this non-dependency clear. Where that documentation goes, I'm not sure.

**Comment by anthrotype** [comment]
any news on moving robofab.pens to a standalone package? It's been a while now.

**Comment by behdad** [comment]
> any news on moving robofab.pens to a standalone package? It's been a while now.

I've thought about this a bit as well; let's talk about it in person next week.

**Comment by davelab6** [comment]
Any news? :)

**Comment by jackjennings** [comment]
I'd be willing to tackle creating a `fontPens` (not particularly correct but in line with `fontTools` and `fontParts`) library if there's a clear list of which pens should be extracted from where. (@typesupply)

**Comment by typesupply** [comment]
I'm all for this after working on fontParts. Here's a list off the top of my head:

From [RoboFab's pens](https://github.com/robofab-developers/robofab/tree/master/Lib/robofab/pens):
- [FlattenPen](https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/pens/filterPen.py#L195)
- [AngledMarginPen](https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/pens/angledMarginPen.py) This looks useful, but I don't know if it is used much.
- [MarginPen](https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/pens/marginPen.py) Same comment as above.
- [ReverseContourPointPen](https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/pens/reverseContourPointPen.py)

From [defcon's pens](https://github.com/typesupply/defcon/tree/ufo3/Lib/defcon/pens):
- [ClockwiseTestPointPen](https://github.com/typesupply/defcon/blob/ufo3/Lib/defcon/pens/clockwiseTestPointPen.py) See [this](https://github.com/typesupply/defcon/issues/15) for an improvement.
- [DecomposeComponentPointPen](https://github.com/typesupply/defcon/blob/ufo3/Lib/defcon/pens/decomposeComponentPointPen.py)

**Comment by twardoch** [comment]
Please see the discussion on https://github.com/behdad/fonttools/pull/539 
I've provided a list of pens there that I could find on Github. 

I've recently used AngledMarginPen :)

**Comment by benkiel** [comment]
From yesterday's work on defcon, MarginPen is what provided glyph.box

**Comment by jackjennings** [comment]
Here's an exhaustive list of pens in the `ufoLib`, `fonttools`, `defcon` and `robofab` packages: https://gist.github.com/jackjennings/074c87230a25b8939428

I checked through @twardoch's very complete list of pens, and for this initial effort it seems more manageable to untangle the mutual dependencies of these 4 libraries rather than try to consolidate all of the pens written.

I'd like to get an up or down on all of pens on the linked checklist.

Pens that should be excluded are those that have hard dependencies on their parent package, or pull in any additional dependency—the `fontPens` package shouldn't have any additional dependencies so that it's easy to pull in to any project. At this point, I'm less interested in degree of usefulness as an eliminating factor, though it could be in the future.

The "abstract" pens are duplicated in a few places, and which of these should be the extracted implementation (if they're not identical) will need to be determined.

It would be helpful for some of the maintainers of these repositories to chime in with any information in regards to which pens from their package wouldn't be useful (ever) outside the context that their used in.

**Comment by anthrotype** [comment]
> The "abstract" pens are duplicated in a few places, and which of these should be the extracted implementation (if they're not identical) will need to be determined.

The `AbstractPen` belongs to fontTools and AFAIK is not duplicated anywhere else. The `AbstractPointPen`, along with the converters between the two protocols, should belong to ufoLib package, as I think Tal has suggested.

> the fontPens package shouldn't have any additional dependencies

So, you want to move all the pens, both the "abstract" and "concrete" ones. I thought we would keep the abstract pens inside the original packages, and only move their concrete implementations to the new package. Requiring fonttools or ufoLib doesn't seem too much (that's already the case), and plus one doesn't really need to import/subclass these abstract pens to implement a pen that works like pen.

@graphicore above suggested to call it "penBox" instead of font-something
> because pens can be useful even if you don't work with fonts. Just to draw vector graphics.

I personally don't have a strong opinion. I'm happy with "fontPens" if you prefer that, as long as this move happens and the dependency on robofab is lifted.

**Comment by anthrotype** [comment]
Let's not forget that the main reason we initiated this move was to take "the good part" of robofab out of robofab to a place where it could be maintained and developed further (UFO3, Python3, new font editors, etc).
This has already happened for the UFO read/write stuff (ufoLib), and it's an ongoing effort with fontParts as regards the font objects and the scripting API.
We could also consolidate both the robofab and fonttools pens to a separate package if you like, but IMO the priority should be given to the robofab pens.

**Comment by jackjennings** [comment]
The motivation for moving the abstract pens outside of their original libraries is that we'd be able to eliminate a sibling dependency, replacing it with a hierarchical dependency which is easier to reason about and manage.

If AbstractPen is left in `ufoLib`, if I wanted to create a library that implemented the pen protocol, I'd have to depend on `ufoLib`, which is a much heavier dependency than a hypothetical library containing only pens. If the library is for something other than fonts, it would seem counterintuitive (to me) to include a UFO-centric library. `ufoLib` seems like it should focus on dealing with UFO attributes, and delegate most of the generic pen protocols to a separate package.

If anything, I think that there is more value in moving the abstract classes into a new dependency.

I'm also not sure that the pen protocol really belongs as a part of the UFO spec. The UFO spec is a file format spec that doesn't dictate how to manipulate the underlying data-structure at a high level. I think that this is good, since other libraries (possibly in other languages)should be able to be UFO compliant without implementing the pen protocol, even if that's a convenient part of how the current `robofab`/`fonttools`/`ufoLib` ecosystem works.

The pens that are duplicated between different packages are:
- AbstractPointPen
- BasePointToSegmentPen
- PointToSegmentPen
- SegmentToPointPen
- GuessSmoothPointPen
- Bounds Pen

Maybe a few others…

**Comment by anthrotype** [comment]
> if I wanted to create a library that implemented the pen protocol, I'd have to depend on ufoLib

you don't. Your can define a `class MyPen(object)` which implements all the `lineTo`, `moveTo` etc. and no one should bother checking `isinstance(pen, AbstractPen)`, as Python will duly raise AttributeError if that's not the case.

I guess the "ownership" of the abstract protocol has more to do with who should be responsible for designing and possibly updating those APIs.

> The pens that are duplicated between different packages are: ...

All the pens you mention were moved from robofab/ufo3k branch to ufoLib, and slightly updated to make them work with python 2 and 3. So the ufoLib version should ideally be taken as reference. The BoundsPen was originally (and still is) inside fontTools and was later copied to robofab, modified to ignore contours with single points which robofab (UFO2) treats as anchors.

**Comment by jackjennings** [comment]
Yes, you can create a generic object subclass, but in practice nearly no one has actually done this.

**Comment by anthrotype** [comment]
all user-defined Python classes are, directly or not, children of the `object` type.

**Comment by jackjennings** [comment]
Yes, I understand that, and I understand how duck typing works. I mean that most of the pens that I just reviewed do not subclass `object`, but do subclass one of the abstract or base classes that have been provided by various libraries.

**Comment by anthrotype** [comment]
If they don't explicitly subclass object, then they will use "old-style" classes in Python 2, and (implicitly) "new-style" classes in Python 3, which will have some impact on e.g. `super()` and the like.

But what I meant was that, for the regular pen usage, it doesn't really matter whether the new pen you define is old-style, new-style or inherits from any of the abstract classes. It simply needs to define all the required methods that are expected from such a pen.

**Comment by jackjennings** [comment]
Again, I understand that. My point is that if you *do* want to subclass the abstract or base versions of Pen or PointPen, does it really make sense to have to require a library that is not specifically and narrowly related to creating pens?

**Comment by anthrotype** [comment]
I guess not. If do not want to depend on them, you don't subclass them.

**Comment by jackjennings** [comment]
I'll wait to hear from other package maintainers, but if there's no buy in for moving the abstract and base classes into a dependency I'm not sure that it's worth the effort to consolidate only pens that derive from them.

**Comment by twardoch** [comment]
Well, I see it as two steps: first create fontPens as a kind of a "plugin collection" while keeping the basic pens in fontTools but providing thin wrappers inside the fontPens package for the base pens. 

At some point later, the reverse can be done: the actual implementation of the base pens can move to fontPens and the fontTools.pens subpackage can become thin wrappers.

**Comment by anthrotype** [comment]
No one wants to depend on a package that is not updated nor maintained. Traditionally robofab would depend on fonttools, which (being lower level) would not depend on anything else. Nobody ever complained about that. Now that robofab is dying (to be born again as fontParts), there is the problem of what to do with the pens, which is the only lingering dependency on robofab that other packages still have.

Another solution that is worth considering (and then I'll shut up! ;) is to move the pens to fontParts as well. I know it's got "fonts" in it, but where are the more general, non-font related implementations?

**Comment by graphicore** [comment]
The real use of the abstract classes is interface documentation. It may be enough to just link to them in the README.

The base classes, that's the most interesting stuff, because you really want to inherit from or use those. It would even make sense to make a lightweight "base pens" package with just `BasePen`, `TransformPen`, `NullPen`(?), `PointToSegmentPen`, `SegmentToPointPen` and a more heavy weight "pen plugin collection" as suggested by @twardoch. Then everything needed to get started with pens is in one (tiny) package. The "base pens" package is probably low effort to maintain, because it won't change much.

**Comment by jackjennings** [comment]
@graphicore That makes sense to me, as it sidesteps the issue of what is important enough to include in the core package to some extent. In the Ruby world, some packages have a corresponding semi-official "contrib" package for commonly used extensions, e.g. [rack](https://github.com/rack/rack)/[rack-contrib](https://github.com/rack/rack-contrib), [sinatra](https://github.com/sinatra/sinatra)/[sinatra-contrib](https://github.com/sinatra/sinatra-contrib).

**Comment by typesupply** [comment]
Let me make sure the terminology is clear:
- **Pen** = fontTools pen protocol. This is a Postscript like, segment oriented protocol. There are moveTo, lineTo, curveTo, etc. methods. This is useful for interfacing with environments that have Postscript oriented drawing environments, like Cocoa. The pen provides a common API on top of that. This protocol is useful for much more than that, but this is a hugely useful thing.
- **Point Pen** (or PointPen) = RoboFab/ufoLib point pen. This is a point, *not segment*, oriented protocol. It's very useful for transferring data within font editing environments. Those typically use more of a point model than a segment model.

Each of these have their merits and unique uses. The **Adapter Pens** environments to implement interfacing with one or the other protocol. For example, defcon is a point oriented environment so it draws to the PointPen protocol natively. The method that handles the Pen protocol imports an adapter pen, wraps the given Pen with that and passes the wrapper to the method that handles the Point Pen protocol. Easy.

I think everyone knows this. I just want to make sure it's clear.

Regarding the relationship between GLIF and Point Pen: The GLIF contour point structure follows the PointPen protocol. Point Pen actually came about because writing GLIF contour points was tricky with the Pen protocol.

In a perfect world, we would have a fontPens packages that would contain the abstract and base implementations of *both* the Pen and Point Pen protocols. This would allow us to have a single source for documentation about  and example implementations of the protocols. That would eliminate the confusion about where the adapters should go, the issues of two dependencies and probably other stuff.

This would also eliminate another issue that I've run into. When I started implementing UFO 3 in defcon, I realized that the Pen protocol didn't allow point identifiers. That would have required a fontTools change and I was reluctant to do that. So, Point Pen -> Pen as of UFO 3 is a lossy translation. If the protocols were both owned by the same package, they could more easily be kept in sync.

The only problem with moving the Pen protocol out of fontTools is that it would create a new dependency for fontTools. If that's a problem, perhaps fontTools could just be considered an independent implementation of the protocol.

**Comment by anthrotype** [comment]
Thanks Tal for the detailed reply. FontTools does not depend on its own pens. The `pens` subpackage is quite independent from the rest of the library. If you search the codebase there are only a couple of places where a NullPen or a BoundsPen is used, but it's not crucial. So I think that is not a problem as far as I'm concerned. /cc @behdad

**Comment by behdad** [comment]
Yes, the pens in fontTools are mostly for user to use, not for fontTools itself.  We can created yet another repo, but I believe both Just and I agree, that we might as well put them all in fonttools.

The reason I've been silent so far is because I have ideas that I want to suggest for the new penBox, but I have not had time to flesh them out yet.

In short, I like to suggest we move away from the current BasePen model that implements moveTo, etc and expects subclasses to implement _moveTo etc; to a mixin model, whereas there are sink pens that implement a few methods, and there are mixin pens that implement some meyhods and might or might not call super() in those.

Then the adaptor pens become mixins.  The quad-to-cubic becomes a mixin.  The track-current-point becomes a mixin.  When writin a new sink pen, eg one to compute area of a glyph, if I need current point attack ng and need quadratic-to-cubic handling, I'll explicitly pull in those mixins as superclasses.

We can alao have a one line way of testing a pen against all kinds of input (None first point, etc) for a given protocol so people can be sure their pen is complete.

I also like to define a ValuePen protocol, which is for sink pens that calculate a value (glyph area, perimeter, hits, ...).  They should all store the result in pen.value.  This allows for writing adaptor pens for ValuePens.  For example a ByContour adaptor that calculates values for each contour separately.  The value pen class can also provide a reduce method as well as initial value of value.

Those are my current thoughts.  As you can see, not fleshed out.

**Comment by jackjennings** [comment]
@behdad I actually agree that it would be interesting to reimagine what the internal API for building pens. What you're describing is a pattern that I like a lot, and leads to a really flexible Interface.

That being said, that's a far more drastic change than simply consolidating some shared functionality into a small dependency. If anything, centralizing some of the pen functionality in one place would provide a place to explore this in a safer and more considered environment before deploying a pen 2.0 interface directly into live code.

**Comment by adrientetar** [comment]
> to a mixin model, 

Is there an actual need for that? It seems a little over-engineering to me.

**Comment by twardoch** [comment]
If we consolidate all the basic pens into a `fontPens` package, then fontTools.pens can be made into a "temporary" passthrough subpackage (thin wrapper) which just does 
`from fontPens.pens import *` 
or something like that, so "legacy" pens don't fail. Over time, pen developers could patch their inheritance to use fontPens.pens instead of fontTools.pens or the RF pointPen. The thin "pens" warapper could live inside fontTools as a legacy thing. 

fontTools proper doesn't really use pens, the core of fontTools really is about SFNT, and frankly, I cannot imagine that the decision to put the original "pens" subpackage inside fontTools was "designed" by Just very consciously. It seems Just put pens in there because at the time he started fontTools, there wasn't another good location for such a tiny package. 

I think we should use the roboFab->fontParts transition to clean it up. I don't think the pens belong structurally to fontTools, ufoLib or fontParts. A separate repo is actually better. There are many situations where one wants to use a pen and doesn't want to use fontTools, fontParts or ufoLib. 

For example, I use a pen to move glyphs between FLS5 and the imported fontforge package, i.e. two "native" font editing environments, without using any otherwise pythonic structures. 

If we go by the argument "you don't need to create a pen by inheritance", then actually it does not matter where the basic pens are stored, so we can dump the base pen classes completely :) But I don't think this is a serious argument. Sure, you don't *need* to inherit, but inheritance is more pythonic and elegant, and it helps documentation and introspection. 

BTW, to compile my list of pens I actually searched Github for the inheritance patterns. So it was useful even now.

**Comment by twardoch** [comment]
Somewhat off-topic: at the Typo Labs Berlin 2016 event (May 10-11) @jenskutilek is giving a workshop about pens: 
http://typotalks.com/labs/schedule/talk/?tid=35743&et=TYPO%20Labs%202016

Perhaps it'd be great if people on this thread make a decision about the future direction by that time, then Jens could incorporate a brief “future plans” statement into his workshop. Or alternatively, since a few of the interested parties will attend TYPO Labs, a brief informal discussion about this could be held there. 

I don’t feel I have enough stakes in pens myself. I’ve voiced my opinion but I trust the maintainers of the relevant packages to come to an agreement about the future direction.

**Comment by behdad** [comment]
> Typo Labs Berlin 2016

It would be the excellent venue to brainstorm the future API, as in 2.0.  In the mean time, someone should just move the robofab pens somewhere else and call this issue closed.

**Comment by twardoch** [comment]
Seems like it started: https://github.com/robofab-developers/fontPens

**Comment by typesupply** [comment]
> Seems like it started: https://github.com/robofab-developers/fontPens

Yeah, I started that. Still thinking about what should go into it. I'm in fontParts land right now and then I'll come back to this.

**Comment by behdad** [comment]
> to a mixin model,
> 
> Is there an actual need for that? It seems a little over-engineering to me.

Right now the BasePen does a bunch of things, including quadratic-to-cubic conversion and tracking current point.  There are more desirable things that a base pen can provide.  But then we end stuffing a set of arbitrary things into a base class.  Since most of these things are independent, we may as well put them in separate classes and use multiple inheritance to pull in exactly the features you need.  That's exactly what mixins are.

**Comment by typemytype** [comment]
finally moved robofab pens to fontPens 

https://github.com/robofab-developers/fontPens/commit/02ce611119e54a21c8b6f6e2b9658ad7f1b7cc9f

@anthrotype could you add those doc testing workers?

also needed to add a `setup.py` and update the `readme`, anyone?

**Comment by typemytype** [comment]
further discussions and issues should be posted on https://github.com/robofab-developers/fontPens/issues
